[package]
name = "us-census-core"
version = "0.1.0"
edition = "2021"
readme = "README.md"
description = "A tool for downloading US Census datasets written in Rust"

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
itertools = { workspace = true }
