name: Test (Rust)

on:
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: cargo test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - name: Formatting
        run: |
          rustup component add rustfmt
          cargo fmt --all -- --check
      - name: Test
        run: |
          cargo test --workspace --verbose
