name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: bam-runners
    steps:
      - name: install rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: debug stub
        run: ls -lh
      - name: test
        run: cargo test
  # test:
  #   name: cargo test
  #   runs-on: bam-runners
  #   steps:
  #     - uses: actions/checkout@v4
  #     - uses: actions-rust-lang/setup-rust-toolchain@v1
  #     - name: import pkgconfig
  #     - run: 
  #     - name: Test
  #     - run: cargo test --all-features
# jobs:
#   build:
#     runs-on: bam-runners
#     steps:
#     - uses: actions/checkout@v4
#     - name: Setup
#       run: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
#     - name: Build
#       run: cargo build --verbose
#     - name: Run tests
#       run: cargo test --verbose
