name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: bam-runners
    steps:
    - uses: actions/checkout@v4
    - name: Setup
      run: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
