name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  # setup:
  #   name: install openssl
  #   runs-on: bam-runners
  #   steps:
  #     # - uses: actions/checkout@v4
  #     - name: install
  #       run: sudo apt-get install libssl-dev
  # test:
  #   runs-on: bam-runners
  #   steps:
  #     - name: install rust
  #       uses: actions-rs/toolchain@v1
  #       with:
  #         profile: minimal
  #         toolchain: stable
  #         override: true
  #     - name: test
  #       run: cargo test
  test:
    name: cargo test
    runs-on: bam-runners
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - name: Test
        run: |
          sudo apt-get install libssl-dev
          cargo test
# jobs:
#   build:
#     runs-on: bam-runners
#     steps:
#     - uses: actions/checkout@v4
#     - name: Setup
#       run: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
#     - name: Build
#       run: cargo build --verbose
#     - name: Run tests
#       run: cargo test --verbose
